package model

import (
	"bytes"
	"encoding/json"

	"github.com/invopop/jsonschema"
)

// ContextSchema returns the JSON Schema for the Context contract, generated by
// reflection over the Go types so it can never silently drift from the struct.
// The committed schema/ file is this output; TestSchema_matchesModel diffs them.
func ContextSchema() []byte {
	return reflectSchema(&Context{},
		"https://pgbot.dev/schema/pgbot-context-"+SchemaVersion+".json",
		"pgbot inspect --json — the versioned Context contract for agents and scripts.")
}

// reflectSchema produces a stable, indented JSON Schema for v.
func reflectSchema(v any, id, description string) []byte {
	r := &jsonschema.Reflector{
		// Emit a self-contained schema (definitions inline under $defs) with field
		// docs pulled from Go comments where available.
		DoNotReference: false,
	}
	s := r.Reflect(v)
	s.ID = jsonschema.ID(id)
	s.Description = description
	b, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		panic(err) // a struct that can't be schema'd is a build-time bug
	}
	return append(bytes.TrimRight(b, "\n"), '\n')
}
