package config

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/pgrundev/pgbot/internal/findings"
	"github.com/pgrundev/pgbot/internal/model"
)

// HygieneWarnings are check-only advisories (not load warnings): they don't stop
// a run, but `pgbot config check` reports them and exits non-zero so CI can hold
// the line. Currently: every [[ignore]] rule should carry an `expires` so the
// suppression gets revisited rather than living forever.
func (c *Config) HygieneWarnings() []string {
	var out []string
	for _, r := range c.Ignore {
		if r.Expires == "" {
			out = append(out, fmt.Sprintf("[[ignore]] %s has no `expires` — add one so the suppression is revisited", r.String()))
		}
	}
	sort.Strings(out)
	return out
}

// Explain reports how the config would treat one finding: any severity remap and
// the most-specific ignore rule that would fire for (id, object). object may be
// empty to ask about the finding's cluster/summary form. It is what turns "why
// isn't my suppression working" into a one-liner.
func (c *Config) Explain(id, object string, now time.Time) string {
	var b strings.Builder
	fmt.Fprintf(&b, "finding: %s\n", id)
	if object != "" {
		fmt.Fprintf(&b, "object:  %s\n", object)
	}
	if !c.knownID(id) {
		fmt.Fprintf(&b, "note:    %q is not a finding this pgbot emits (typo?)\n", id)
	}
	if sv, ok := c.Severity[id]; ok {
		fmt.Fprintf(&b, "severity: remapped to %q by [severity]\n", sv)
	} else {
		fmt.Fprintln(&b, "severity: unchanged (no [severity] override)")
	}
	if rule, ok := c.matchIgnore(id, object, now); ok {
		fmt.Fprintf(&b, "ignore:   SUPPRESSED by rule `%s`\n", rule.String())
		if rule.Reason != "" {
			fmt.Fprintf(&b, "reason:   %s\n", rule.Reason)
		}
		if rule.Expires != "" {
			fmt.Fprintf(&b, "expires:  %s\n", rule.Expires)
		}
	} else {
		// Distinguish "no rule at all" from "a rule exists but is expired / its glob
		// doesn't match" — the two most common 'why isn't it working' cases.
		if shadow := c.nearestRule(id); shadow != nil {
			fmt.Fprintf(&b, "ignore:   NOT suppressed — a rule for %s exists (%s) but did not match", id, shadow.String())
			switch {
			case expired(*shadow, now):
				fmt.Fprint(&b, " (it has expired)\n")
			case shadow.Object != "" && object == "":
				fmt.Fprintf(&b, " (it targets object %q; ask again with that object)\n", shadow.Object)
			case shadow.Object != "":
				fmt.Fprintf(&b, " (its glob %q doesn't match %q)\n", shadow.Object, object)
			default:
				fmt.Fprint(&b, "\n")
			}
		} else {
			fmt.Fprintf(&b, "ignore:   NOT suppressed — no [[ignore]] rule for %s\n", id)
		}
	}
	return b.String()
}

// nearestRule returns the first ignore rule for id regardless of object/expiry,
// so Explain can say "a rule exists but didn't match".
func (c *Config) nearestRule(id string) *IgnoreRule {
	for i := range c.Ignore {
		if c.Ignore[i].Finding == id {
			return &c.Ignore[i]
		}
	}
	return nil
}

func (c *Config) knownID(id string) bool { return findings.KnownID(id) }

// InitTemplate renders a commented .pgbot.toml seeded from a run's findings: each
// finding becomes a commented-out [[ignore]] rule the user uncomments to mute,
// pre-filled with the correct object. Only `schema` is active, so the file loads
// cleanly (and mutes nothing) until edited — see the round-trip test.
func InitTemplate(fs []model.Finding, now time.Time) string {
	var b strings.Builder
	b.WriteString("# .pgbot.toml — pgbot configuration (generated by `pgbot config init`)\n")
	b.WriteString("# Uncomment a rule below to suppress that finding. Add an `expires` date so\n")
	b.WriteString("# the suppression gets revisited. Docs: docs/configuration.md\n\n")
	b.WriteString("schema = 1\n\n")

	b.WriteString("# [thresholds]  — override a detection threshold (finding never fires below it)\n")
	b.WriteString("# unused_index_min_size_mb = 100\n")
	b.WriteString("# dead_ratio_warn          = 0.30\n")
	b.WriteString("# replica_lag_warn_seconds = 30\n\n")

	b.WriteString("# [severity]  — remap a finding's severity (does not remove it)\n")
	b.WriteString("# checksums_disabled = \"info\"   # e.g. on a managed provider you can't change\n\n")

	// Dedup by (id, object) so a summary finding seeds one rule, not ten.
	seen := map[string]bool{}
	expiry := now.UTC().AddDate(0, 0, 90).Format(expiryLayout)
	wrote := 0
	for _, f := range fs {
		key := f.ID + "\x00" + f.Object
		if seen[key] {
			continue
		}
		seen[key] = true
		wrote++
		b.WriteString("# " + oneLine(f.Title) + "\n")
		b.WriteString("# [[ignore]]\n")
		b.WriteString("# finding = \"" + f.ID + "\"\n")
		if f.Object != "" {
			b.WriteString("# object  = \"" + f.Object + "\"\n")
		}
		b.WriteString("# reason  = \"\"\n")
		b.WriteString("# expires = \"" + expiry + "\"\n\n")
	}
	if wrote == 0 {
		b.WriteString("# (no findings this run — nothing to pre-seed)\n")
	}
	return b.String()
}

// oneLine flattens a title to a safe single comment line.
func oneLine(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "\n", " "), "\r", " ")
}
